"use strict";

const card = {
	actions: { type: 'action', fields: 'all', filter: 'all', limit: '1000',  member: 'false', memberCreator: 'false' },
	badges: 'default',
	board: { type: 'board', fields: 'all' },
	checkItemStates: 'default',
	checklists: { type: 'checklist', checkItem_fields: 'all', fields: 'all', filter: 'all' },
	closed: 'default',
	dateLastActivity: 'default',
	desc: 'default',
	descData: 'default',
	due: 'default',
	email: 'default',
	id: 'default',
	idAttachmentCover: 'default',
	idChecklists: 'default',
	idLabels: 'default',
	idList: 'default',
	idMembersVoted: 'default',
	idShort: 'default',
	labels: { type: 'label' },
	list: { type: 'list', fields: 'all' },
	manualCoverAttachment: 'default',
	members: { type: 'member', fields: 'all' },
	membersVoted: { type: 'member', fields: 'all' },
	name: 'default',
	pos: 'default',
	shortLink: 'default',
	shortUrl: 'default',
	subscribed: 'default',
	url: 'default',
};

module.exports = card;
