const member = {
	actions: { trelloType: 'action', fields: 'all', filter: 'all', limit: '1000', member: 'false', memberCreator: 'false' },
	avatarHash: 'default',
	avatarSource: 'default',
	boardBackgrounds: { },
	boards: { trelloType: 'board', fields: 'all', filter: 'all' },
	boardsInvited: { },
	boardStars: { },
	bio: 'default',
	bioData: 'default',
	cards: { trelloType: 'card', fields: 'all', filter: 'all' },
	confirmed: 'default',
	customBoardBacgkrounds: { },
	email: 'default',
	fullName: 'default',
	gravatarHash: 'default',
	id: 'default',
	idBoards: 'default',
	idBoardsPinned: 'default',
	idOrganizations: 'default',
	idPremOrgsAdmin: 'default',
	initials: 'default',
	loginTypes: 'default',
	memberType: 'default',
	notifications: { trelloType: 'notification', fields: 'all', filter: 'all', limit: '1000', memberCreator: 'false', 'read_filter': 'all' },
	oneTimeMessagesDismissed: 'default',
	organizations: { trelloType: 'organization', fields: 'all', filter: 'all' },
	organizationsInvited: { trelloType: 'organization', fields: 'all', filter: 'all' },
	prefs: 'default',
	premiumFeatures: 'default',
	products: 'default',
	savedSearches: { },
	status: 'default',
	tokens: { trelloType: 'token', filter: 'all' },
	trophies: 'default',
	uploadedAvatarHash: 'default',
	url: 'default',
	username: 'default'
};

module.exports = member;
